import { solvePart2 } from "./solution";

const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe("solvePart2", () => {
  it("should return 40 for the example input", () => {
    expect(solvePart2(exampleInput)).toBe(40);
  });

  it("should return 1 when beam exits without hitting any splitter (single timeline)", () => {
    const noSplitInput = `.S.
...
...`;
    expect(solvePart2(noSplitInput)).toBe(1);
  });

  it("should return 2 for a single splitter (two timelines: left and right)", () => {
    const singleSplit = `.S.
...
.^.`;
    expect(solvePart2(singleSplit)).toBe(2);
  });

  it("should return 4 for two levels of splitting", () => {
    // S hits first splitter (2 timelines), then each timeline hits a splitter (4 total)
    const twoLevelSplit = `..S..
.....
..^..
.....
.^.^.`;
    expect(solvePart2(twoLevelSplit)).toBe(4);
  });
});
